### ISSUE TITLE
Training pose based action classification methods using only skeleton data

### ISSUE THREAD

**Issue by vaithak** [IkeaASM/IKEA_ASM_Dataset#12]
How can I train the pose based models for action recognition (like st-GCN) using only the skeleton data (without downloading the images and video data)? I tried using the `train.py` file in the `action/pose_based` directory, but it only allows two load_modes, either video or image. 
If I try to run it using only skeleton data, I get this error:
```
Number of clips in the dataset:0
../clip_based/i3d/i3d_utils.py:81: RuntimeWarning: invalid value encountered in double_scalars
  weight_per_class[i] = N/float(label_count[i])
Traceback (most recent call last):
  File "train.py", line 246, in <module>
    run(dataset_path=args.dataset_path, logdir=args.logdir,
  File "train.py", line 66, in run
    sampler = torch.utils.data.sampler.WeightedRandomSampler(weights, len(weights))
  File "/home/vaibhav/anaconda3/lib/python3.8/site-packages/torch/utils/data/sampler.py", line 176, in __init__
    raise ValueError("num_samples should be a positive integer "
ValueError: num_samples should be a positive integer value, but got num_samples=0
```

**Comment by sitzikbs** [comment]
The code was designed to load the image as well. You can edit the code to skip the image loading to circumvent this.

**Comment by vaithak** [comment]
Thanks 👍
